[[CURRENCIES]]
code="MUSK"
issuer="GDZPQDHTEFSZV2QNS3TFPMVGJVKDACEEEBRD6XEKWJGLHHCZD767FFNJ"
name="Wang Xusheng MUSK"
desc="This is a test MUSK token on Pi Testnet with a total supply of 100000000."
image="https://MUSK1688MUSK.github.io/MUSK.png"
